# This file is covered by the LICENSE file in the root of this project.
name: "mcd"
labels:
  0: "barrier"
  1: "bike"
  2: "building"
  3: "chair"
  4: "cliff"
  5: "container"
  6: "curb"
  7: "fence"
  8: "hydrant"
  9: "infosign"
  10: "lanemarking"
  11: "noise"
  12: "other"
  13: "parkinglot"
  14: "pedestrian"
  15: "pole"
  16: "road"
  17: "shelter"
  18: "sidewalk"
  19: "stairs"
  20: "structure-other"
  21: "traffic-cone"
  22: "traffic-sign"
  23: "trashbin"
  24: "treetrunk"
  25: "vegetation"
  26: "vehicle-dynamic"
  27: "vehicle-other"
  28: "vehicle-static"
color_map: # bgr
  0: [128, 128, 128]  # barrier
  1: [119, 11, 32]    # bike
  2: [0, 100, 0]      # building
  3: [139, 69, 19]    # chair
  4: [101, 67, 33]    # cliff
  5: [160, 160, 160]  # container
  6: [244, 35, 232]   # curb
  7: [190, 153, 153]  # fence
  8: [255, 165, 0]    # hydrant
  9: [255, 255, 0]    # infosign
  10: [170, 255, 150] # lanemarking
  11: [0, 0, 0]       # noise
  12: [255, 255, 50]  # other
  13: [250, 170, 160] # parkinglot
  14: [220, 20, 60]   # pedestrian
  15: [153, 153, 153] # pole
  16: [128, 64, 128]  # road
  17: [0, 100, 0]     # shelter
  18: [244, 35, 232]  # sidewalk
  19: [128, 0, 128]   # stairs
  20: [0, 150, 255]   # structure-other
  21: [255, 69, 0]    # traffic-cone
  22: [0, 0, 255]     # traffic-sign
  23: [139, 0, 139]   # trashbin
  24: [0, 60, 135]    # treetrunk
  25: [107, 142, 35]  # vegetation
  26: [245, 150, 100] # vehicle-dynamic
  27: [51, 0, 51]     # vehicle-other
  28: [0, 0, 142]     # vehicle-static
content: # as a ratio with the total number of points
  0: 0.0004964098
  1: 0.0032825567
  2: 0.3847619272
  3: 0.0017111399
  4: 0.0090896913
  5: 0.0000755138
  6: 0.0040267028
  7: 0.0046319769
  8: 0.0000000000
  9: 0.0013554483
  10: 0.0000445265
  11: 0.0199208713
  12: 0.0045434075
  13: 0.0023278386
  14: 0.0805972382
  15: 0.0032872571
  16: 0.0501524326
  17: 0.0005343171
  18: 0.1660372138
  19: 0.0254111778
  20: 0.0208473085
  21: 0.0001002078
  22: 0.0014933917
  23: 0.0011714296
  24: 0.0061690324
  25: 0.1915667332
  26: 0.0038553015
  27: 0.0000000000
  28: 0.0125089481
# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0: 0    # barrier
  1: 1    # bike
  2: 2    # building
  3: 3    # chair
  4: 4    # cliff
  5: 5    # container
  6: 6    # curb
  7: 7    # fence
  8: 8    # hydrant
  9: 9    # infosign
  10: 10  # lanemarking
  11: 11  # noise
  12: 12  # other
  13: 13  # parkinglot
  14: 14  # pedestrian
  15: 15  # pole
  16: 16  # road
  17: 17  # shelter
  18: 18  # sidewalk
  19: 19  # stairs
  20: 20  # structure-other
  21: 21  # traffic-cone
  22: 22  # traffic-sign
  23: 23  # trashbin
  24: 24  # treetrunk
  25: 25  # vegetation
  26: 26  # vehicle-dynamic
  27: 27  # vehicle-other
  28: 28  # vehicle-static
learning_map_inv: # inverse of previous map
  0: 0
  1: 1
  2: 2
  3: 3
  4: 4
  5: 5 
  6: 6
  7: 7
  8: 8
  9: 9
  10: 10
  11: 11
  12: 12
  13: 13
  14: 14
  15: 15
  16: 16
  17: 17
  18: 18
  19: 19
  20: 20
  21: 21
  22: 22
  23: 23
  24: 24
  25: 25
  26: 26
  27: 27
  28: 28
learning_ignore: # Ignore classes
  0: False
  1: False
  2: False
  3: False
  4: False
  5: False
  6: False
  7: False
  8: False
  9: False
  10: False
  11: False
  12: False
  13: False
  14: False
  15: False
  16: False
  17: False
  18: False
  19: False
  20: False
  21: False
  22: False
  23: False
  24: False
  25: False
  26: False
  27: False
  28: False

# For MCD Training
sequences: ["kth_day_09"]
split: [0.8, 0.1, 0.1] # train, valid, test (used only during training)