# This file is covered by the LICENSE file in the root of this project.
name: "mcd"
labels:
  0: "barrier"
  1: "bike"
  2: "building"
  3: "chair"
  4: "cliff"
  5: "container"
  6: "curb"
  7: "fence"
  8: "hydrant"
  9: "infosign"
  10: "lanemarking"
  11: "noise"
  12: "other"
  13: "parkinglot"
  14: "pedestrian"
  15: "pole"
  16: "road"
  17: "shelter"
  18: "sidewalk"
  19: "stairs"
  20: "structure-other"
  21: "traffic-cone"
  22: "traffic-sign"
  23: "trashbin"
  24: "treetrunk"
  25: "vegetation"
  26: "vehicle-dynamic"
  27: "vehicle-other"
  28: "vehicle-static"
color_map: # bgr
  0: [128, 128, 128]  # barrier
  1: [119, 11, 32]    # bike
  2: [0, 100, 0]      # building
  3: [139, 69, 19]    # chair
  4: [101, 67, 33]    # cliff
  5: [160, 160, 160]  # container
  6: [244, 35, 232]   # curb
  7: [190, 153, 153]  # fence
  8: [255, 165, 0]    # hydrant
  9: [255, 255, 0]    # infosign
  10: [170, 255, 150] # lanemarking
  11: [0, 0, 0]       # noise
  12: [255, 255, 50]  # other
  13: [250, 170, 160] # parkinglot
  14: [220, 20, 60]   # pedestrian
  15: [153, 153, 153] # pole
  16: [128, 64, 128]  # road
  17: [0, 100, 0]     # shelter
  18: [244, 35, 232]  # sidewalk
  19: [128, 0, 128]   # stairs
  20: [0, 150, 255]   # structure-other
  21: [255, 69, 0]    # traffic-cone
  22: [0, 0, 255]     # traffic-sign
  23: [139, 0, 139]   # trashbin
  24: [0, 60, 135]    # treetrunk
  25: [107, 142, 35]  # vegetation
  26: [245, 150, 100] # vehicle-dynamic
  27: [51, 0, 51]     # vehicle-other
  28: [0, 0, 142]     # vehicle-static
content: # as a ratio with the total number of points
  0: 
  1: 
  2: 
  3: 
  4:
  5:
  6:
  7:
  8:
  9:
  10:
  11:
  12:
  13:
  14:
  15:
  16:
  17:
  18:
  19:
  20:
  21:
  22:
  23:
  24:
  25:
  26:
  27: 
  28:
# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0: 0     # "unlabeled"
  1: 0     # "outlier" mapped to "unlabeled" --------------------------mapped
  10: 1     # "car"
  11: 2     # "bicycle"
  13: 5     # "bus" mapped to "other-vehicle" --------------------------mapped
  15: 3     # "motorcycle"
  16: 5     # "on-rails" mapped to "other-vehicle" ---------------------mapped
  18: 4     # "truck"
  20: 5     # "other-vehicle"
  30: 6     # "person"
  31: 7     # "bicyclist"
  32: 8     # "motorcyclist"
  40: 9     # "road"
  44: 10    # "parking"
  46: 11    # "osm-road"
  48: 12    # "sidewalk"
  49: 13    # "other-ground"
  50: 14    # "building"
  45: 15    # "osm-building"
  51: 16    # "fence"
  52: 0     # "other-structure" mapped to "unlabeled" ------------------mapped
  60: 9     # "lane-marking" to "road" ---------------------------------mapped
  70: 17    # "vegetation"
  71: 18    # "trunk"
  72: 19    # "terrain"
  80: 20    # "pole"
  81: 21    # "traffic-sign"
  99: 0     # "other-object" to "unlabeled" ----------------------------mapped
  252: 1    # "moving-car" to "car" ------------------------------------mapped
  253: 7    # "moving-bicyclist" to "bicyclist" ------------------------mapped
  254: 6    # "moving-person" to "person" ------------------------------mapped
  255: 8    # "moving-motorcyclist" to "motorcyclist" ------------------mapped
  256: 5    # "moving-on-rails" mapped to "other-vehicle" --------------mapped
  257: 5    # "moving-bus" mapped to "other-vehicle" -------------------mapped
  258: 4    # "moving-truck" to "truck" --------------------------------mapped
  259: 5    # "moving-other"-vehicle to "other-vehicle" ----------------mapped
learning_map_inv: # inverse of previous map
  0: 0      # "unlabeled", and others ignored
  1: 10     # "car"
  2: 11     # "bicycle"
  3: 15     # "motorcycle"
  4: 18     # "truck"
  5: 20     # "other-vehicle"
  6: 30     # "person"
  7: 31     # "bicyclist"
  8: 32     # "motorcyclist"
  9: 40     # "road"
  10: 44    # "parking"
  11: 46    # "osm-road"
  12: 48    # "sidewalk"
  13: 49    # "other-ground"
  14: 50    # "building"
  15: 45    # "osm-building"
  16: 51    # "fence"
  17: 70    # "vegetation"
  18: 71    # "trunk"
  19: 72    # "terrain"
  20: 80    # "pole"
  21: 81    # "traffic-sign"
learning_ignore: # Ignore classes
  0: True      # "unlabeled", and others ignored
  1: False     # "car"
  2: False     # "bicycle"
  3: False     # "motorcycle"
  4: False     # "truck"
  5: False     # "other-vehicle"
  6: False     # "person"
  7: False     # "bicyclist"
  8: False     # "motorcyclist"
  9: False     # "road"
  10: False    # "parking"
  11: False    # "osm-road"
  12: False    # "sidewalk"
  13: False    # "other-ground"
  14: False    # "building"
  15: False    # "osm-building"
  16: False    # "fence"
  17: False    # "vegetation"
  18: False    # "trunk"
  19: False    # "terrain"
  20: False    # "pole"
  21: False    # "traffic-sign"
split: # sequence numbers
  test:   # For inference
    - "day_09"
  train:
    - "day_10"
    - "night_04"
    - "night_01"
  valid:
    - 5
    - 6
    - 9

# For CU-Multi
train_robots: ["robot3", "robot4"]
val_robots: ["robot1"]
test_robots: ["robot2"]