# TODO: Use dataset_name to determine paths of other fields
dataset_path: /media/donceykong/doncey_ssd_02/datasets/MCD
dataset_name: MCD  # "KITTI-360" or "CU-MULTI" or "MCD"
infer_or_train: infer   # "train" or "infer"
# data_config: /home/donceykong/Desktop/ARPG/projects/fall_2024/Lidar2OSM_FULL/Lidar2OSM/lidar2osm/config/labels/semantic-kitti_MCD.yaml
data_config: /home/donceykong/Desktop/ARPG/projects/fall_2024/Lidar2OSM_FULL/Lidar2OSM/lidar2osm/config/labels/semantic-kitti.yaml

inference:
  # model_path: /media/donceykong/donceys_data_ssd/models/CENet/cumulti_osm/cenet_osm-512
  model_path: /media/donceykong/donceys_data_ssd/models/CENet/semantic_kitti/1024_valid5
  split: test # "valid", "train", or "test"

training:
  model_name: cenet_osm-512
  use_progressive_growing: True

  model_configs:
    cenet_osm-512:
      arch_config: ./config/arch/train/cenet_osm-512.yaml
      model_name: cenet_osm-512

    cenet_osm-1024:
      arch_config: ./config/arch/train/cenet_osm-1024p.yaml
      model_name: cenet_osm-1024
      pretrained_model_path: ./models/cumulti_osm_style/cenet_osm-512

    cenet_osm-2048:
      arch_config: ./config/arch/train/cenet_osm-2048p.yaml
      model_name: cenet_osm-2048
      pretrained_model_path: ./models/cumulti_osm_style/cenet_osm-1024