# TODO: Use dataset_name to determine paths of other fields
dataset_path: /media/donceykong/doncey_ssd_02/datasets/MCD
dataset_name: MCD    # "KITTI-360", "CU-MULTI", or "MCD"
infer_or_train: train     # "train" or "infer"
data_config: /home/donceykong/Desktop/ARPG/projects/fall_2024/Lidar2OSM_FULL/Lidar2OSM/lidar2osm/config/data_cfg_mcd.yaml

training:
  model_path: /media/donceykong/donceys_data_ssd/models/CENet/mcd_style
  model_name: cenet_mcd-512
  use_progressive_growing: True

  model_configs:
    cenet_mcd-512:
      arch_config: /home/donceykong/Desktop/ARPG/projects/fall_2024/Lidar2OSM_FULL/Lidar2OSM/lidar2osm/config/arch/train/cenet_mcd-512.yaml
      model_name: cenet_mcd-512

    cenet_mcd-1024:
      arch_config: /home/donceykong/Desktop/ARPG/projects/fall_2024/Lidar2OSM_FULL/Lidar2OSM/lidar2osm/config/arch/train/cenet_mcd-1024p.yaml
      model_name: cenet_mcd-1024
      pretrained_model_path: /media/donceykong/donceys_data_ssd/models/CENet/mcd_style/cenet_mcd-512

    cenet_mcd-2048:
      arch_config: /home/donceykong/Desktop/ARPG/projects/fall_2024/Lidar2OSM_FULL/Lidar2OSM/lidar2osm/config/arch/train/cenet_mcd-2048p.yaml
      model_name: cenet_mcd-2048
      pretrained_model_path: /media/donceykong/donceys_data_ssd/models/CENet/mcd_style/cenet_mcd-1024